import Head from 'next/head'
import EventCard from '../components/EventCard'

export async function getServerSideProps() {
  const [eventsRes, weatherRes] = await Promise.all([
      fetch("http://opentechcalendar.co.uk/api1/events.json"), 
      fetch("http://api.openweathermap.org/data/2.5/forecast?id=524901&appid=712c94ba273be5295b3a0cc73ddffa51")
    ]);
    const [events, weather] = await Promise.all([
      eventsRes.json(), 
      weatherRes.json()
    ]);
    return {
      props: {
        data: events.data,
        weather: weather.weather
      }
  }
}

export default function WeatherTest({ data, weather }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="eventContainer">
         {data.map((item, id) => {
            return (
              <div key={id}>
                <EventCard 
                  summary={item.summary} 
                  displaylocal={item.start.displaylocal} 
                />
              </div>
            )
          })}
          {weather.map((item, id) => {
            return (
              <div key={id}>
                {item.cod}
              </div>
            )
          })}
        </div>      
      </main>
    </div>
  )
}
